### ISSUE TITLE
Plz, help with "No algorithm worked! [Op:Conv2D]"

### ISSUE THREAD

**Issue by SolicTous** [vincent1bt/Real-ESRGAN-TensorFlow#1]
Project looks very fine)
But can't start training with error in Op:Conv2D in conv() operation from gaussian

tf 2.7.0 / 2.4.4
cuda 11.2 / 11.0
tfa-nightly

Moreother simple mnist is working on cuda (https://www.tensorflow.org/tutorials/quickstart/beginner)

Traceback (most recent call last):
  File "train.py", line 139, in <module>
    train(epochs)
  File "train.py", line 116, in train
    gt_img, lq_img = feed_data(img, first_kernel, second_kernel, sinc_kernel, [feed_props_1, feed_props_2])
  File "/RealESRGAN/data_generator/data_generator.py", line 142, in feed_data
    usm_imgs = usm_sharpener.sharp(imgs)
  File "........................./RealESRGAN/data_generator/data_utils.py", line 98, in sharp
    blur = gaussian_filter2d(imgs, self.kernel)
  File "........................./RealESRGAN/data_generator/data_utils.py", line 80, in gaussian_filter2d
    imgs = conv(imgs)
  File "................................/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "................................/venv/lib/python3.8/site-packages/tensorflow/python/keras/layers/convolutional.py", line 248, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "................................/venv/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "................................/venv/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 1013, in convolution_v2
    return convolution_internal(
  File "................................/venv/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 1143, in convolution_internal
    return op(
  File "................................/venv/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 2597, in _conv2d_expanded_batch
    return gen_nn_ops.conv2d(
  File "................................/venv/lib/python3.8/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 932, in conv2d
    _ops.raise_from_not_ok_status(e, name)
  File "................................/venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
**tensorflow.python.framework.errors_impl.NotFoundError: No algorithm worked! [Op:Conv2D]**

**Comment by SolicTous** [comment]
Solved by https://github.com/tensorflow/tensorflow/issues/43174#issuecomment-691657692
